[package]
name = "wits"
version = "0.1.0"
edition = "2024"

[lib]
name = "wits"
path = "src/lib.rs"

[[bin]]
name = "wits"
path = "src/bin/main.rs"

[dependencies]
anyhow.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
scraper.workspace = true
clap.workspace = true
colored.workspace = true

[dev-dependencies]
wiremock = "0.6"
tokio = { workspace = true, features = ["full"] }
